### ISSUE TITLE
"Person" and its subclasses "Initiator" and "Operator"

### ISSUE THREAD

**Issue by HosseinBeygiNasrabadi** [materialdigital/core-ontology#102]
"Person" can be restructured as a subclass of "Object".
"Initiator" and "Operator" are better defined as "Role" not "Person"

**Comment by joergwa** [comment]
Person is now sc Object.
Initiator (as well as Operator) is defined equivalent to "Person and ('has role' some 'Initiator Role')". 
So these roles already exist.
