### ISSUE TITLE
Add and describe DateTime (timestamp)

### ISSUE THREAD

**Issue by joergwa** [materialdigital/core-ontology#11]

**Comment by henkbirkholz** [comment]
First we have to understand what we want to do here.
There are two prominent options:
1. A composite value of calendar values (the counting of days and years) & time values (the counting of seconds) as defined in, for exmaple:
    * https://www.rfc-editor.org/rfc/rfc3339#section-5.6 and
    * "Data elements and interchange formats -- Information interchange -- Representation of dates and times", ISO 8601:1988(E), International Organization for Standardization, June, 1988.
2. A time value as defined in, for exmaple:
    * IEEE Std 1003.1-2017 "IEEE Standard for Information Technology--Portable Operating System Interface (POSIX(TM)) Base Specifications"

Do we want both? Do we need both?

**Comment by joergwa** [comment]
use time ontology https://www.w3.org/TR/owl-time/
