### ISSUE TITLE
Check Chemical Composition to model lists of "Masseanteil"

### ISSUE THREAD

**Issue by joergwa** [materialdigital/core-ontology#12]
For example: 
{
"C": "0.448",
"Si": "0.313",
"Mn": "0.825",
"P": "0.019",
"S": "0.032",
"Cr": "0.99",
"Mo": "0.175",
"Ni": "0.044",
"Al": "0.029",
"B": "nnw.",
"Cu": "0.041",
"N": "0.010",
"Co": "<0,015",
"W": "nnw.",
"V": "0.010",
"Ti": "<0,02",
"Zr": "nnw.",
"Nb": "nnw.",
"Ta": "nnw.",
"As": "0.004",
"Sn": "0.016"}

**Comment by JannisGrundmann** [comment]
CHEBI in subset??? in_subset (ebi.ac.uk)
https://www.ebi.ac.uk/ols/ontologies/chebi/properties?iri=http%3A%2F%2Fwww.geneontology.org%2Fformats%2FoboInOwl%23inSubset&lang=en&viewMode=All&siblings=false

**Comment by JannisGrundmann** [comment]
https://qudt.org/vocab/quantitykind/MassFraction

**Comment by JannisGrundmann** [comment]
https://schema.space/metasat/massFraction

**Comment by JannisGrundmann** [comment]
https://liusemweb.github.io/mdo/structure/1.1/index.html#Composition

**Comment by JannisGrundmann** [comment]
pmde:1da483 a pmdco:ChemicalComposition .
        
pmdco:ChemicalComposition owl:subClassOf pmdco:ValueObject .


pmde:20ae03 a pmdco:ChemicalElement ;
    rdfs:label "Aluminium"@en ;
    pmdco:relatesToElement chebi:28984 ;
    pmdco:hasUnit qudt:MassFraction ;
    pmdco:hasValue "0.029"^^xsd:float ;
    dcterms:isPartOf pmde:1da483 .


pmde:0f8cfbe a pmdelem:Titanium ;
    rdfs:label "Titanium"@en ;
    pmdco:hasUnit qudt:MassFraction ;
    pmdco:relatesToElement chebi:155870 ;
    dcterms:isPartOf pmde:1da483 .
    pmdco:hasValueMax "0.02"^^xsd:float . #  pmdco:hasValue "<0,02"^^xsd:string .



pmde:12fcffd2 a pmdelem:Zirconium ;
    rdfs:label "Zirconium"@en ;
    pmdco:hasUnit qudt:MassFraction ;
    pmdco:relatesToElement chebi:33342 ;
    dcterms:isPartOf pmde:1da483 .
    pmdco:hasValue false . # false prepresents "nnw." (nicht nachweissbar)

**Comment by joergwa** [comment]
ex:proc1 pmd:hasChacteristic ex:vo1 .

ex:vo1 a ValueObject .
ex:vo1 hasResource ex:chemComp1 .
ex:chemComp1 a pmd:ChemicalComposition .

ex:vo2 dcterm:partOf ex:chemComp1 .
ex:vo2 a pmd:chemicalElement .
ex:vo2 pmd:relatesToElement chebi12234_AL .
ex:vo2 pmd:relatesTo ex:vo3 .

pmd:MassFraction subClass ValueObject .
ex:vo3 a MassFraction .
ex:vo3 qudt:upperBound "0.3" .
ex:vo3 qudt:lowerBound "0" .
ex:vo3 qudt:hasUnit qudt:PERCENT .

ex:vo4 a MassFraction .
ex:vo4 pmd:hasResource pmd:notDetected .
