### ISSUE TITLE
Provide Descriptions for following classes:

### ISSUE THREAD

**Issue by joergwa** [materialdigital/core-ontology#13]
- [x]  <http://material-digital.de/pmdco/BaseMaterial>		
- [x]  <http://material-digital.de/pmdco/CalibrationDocument>		
- [x]  <http://material-digital.de/pmdco/ChangeOfTransverseDimension>		
- [x]  <http://material-digital.de/pmdco/ComputingNode>		
- [x]  <http://material-digital.de/pmdco/ElementalComposition>		
- [x]  <http://material-digital.de/pmdco/PlanningProcess>

**Comment by henkbirkholz** [comment]
http://material-digital.de/pmdco/PlanningProcess

Moved to next update. Not included for know (despite PROV-O plan)

**Comment by MarkusSchilling** [comment]
All classes mentioned in this issue were defined.

Note: http://material-digital.de/pmdco/ElementalComposition was replaced by 'chemical object', 'chemical composition' and 'chemical entity' (CHEBI-related).
