### ISSUE TITLE
Provide german labels

### ISSUE THREAD

**Issue by joergwa** [materialdigital/core-ontology#14]
- [x] <http://material-digital.de/pmdco/2DPixelCoordinates>
- [x] <http://material-digital.de/pmdco/Acoustical>
- [x] <http://material-digital.de/pmdco/Address>
- [x] <http://material-digital.de/pmdco/AgingInterval>
- [x] <http://material-digital.de/pmdco/AgingProcess>
- [x] <http://material-digital.de/pmdco/AgingTemperature>
- [x] <http://material-digital.de/pmdco/AgingTime>
- [x] <http://material-digital.de/pmdco/Algorithm>
- [x] <http://material-digital.de/pmdco/AmorphousStructure>
- [x] <http://material-digital.de/pmdco/AnalysingProcess>
- [x] <http://material-digital.de/pmdco/AssemblingProcess>
- [ ] <http://material-digital.de/pmdco/BaseMaterial>
- [x] <http://material-digital.de/pmdco/Biological>
- [ ] <http://material-digital.de/pmdco/Blank>
- [x] <http://material-digital.de/pmdco/BondingType>
- [x] <http://material-digital.de/pmdco/BrinellHardnessTest>
- [ ] <http://material-digital.de/pmdco/ChangeOfTransverseDimension>
- [x] <http://material-digital.de/pmdco/Chemical>
- [x] <http://material-digital.de/pmdco/ChemicalElement>
- [x] <http://material-digital.de/pmdco/Circular>
- [x] #16
- [x] <http://material-digital.de/pmdco/CommissionTime>
- [x] <http://material-digital.de/pmdco/Component>
- [x] <http://material-digital.de/pmdco/CompressionTest>
- [x] <http://material-digital.de/pmdco/ComputingNode>
- [x] <http://material-digital.de/pmdco/Coordinates>
- [x] <http://material-digital.de/pmdco/CovalentBond>
- [x] <http://material-digital.de/pmdco/CreepStress>
- [x] <http://material-digital.de/pmdco/CrossSectionDetermination>
- [x] <http://material-digital.de/pmdco/CrystallineStructure>
- [ ] <http://material-digital.de/pmdco/DataCiteMetadata>
- [x] <http://material-digital.de/pmdco/DataScope>
- [x] <http://material-digital.de/pmdco/Date>
- [x] <http://material-digital.de/pmdco/DemountingProcess>
- [x] <http://material-digital.de/pmdco/Department>
- [x] <http://material-digital.de/pmdco/Diameter>
- [ ] <http://material-digital.de/pmdco/DigitalMaterialIdentifier>
- [x] <http://material-digital.de/pmdco/Distance>
- [x] <http://material-digital.de/pmdco/Document>
- [x] <http://material-digital.de/pmdco/Duration>
- [x] <http://material-digital.de/pmdco/Electrical>
- [x] <http://material-digital.de/pmdco/ElectronMicroscope>
- [x] <http://material-digital.de/pmdco/ElectronMicroscopy>
- [x] <http://material-digital.de/pmdco/ElementalComposition>
- [x] <http://material-digital.de/pmdco/Elliptical>
- [x] <http://material-digital.de/pmdco/EndTime>
- [x] <http://material-digital.de/pmdco/EngineeringMaterial>
- [x] <http://material-digital.de/pmdco/Extensometer>
- [x] <http://material-digital.de/pmdco/FeretDiameter>
- [x] <http://material-digital.de/pmdco/Filter>
- [x] <http://material-digital.de/pmdco/FinalProcess>
- [x] <http://material-digital.de/pmdco/Force>
- [x] <http://material-digital.de/pmdco/Furnace>
- [x] <http://material-digital.de/pmdco/FurnaceCharacteristic>
- [x] <http://material-digital.de/pmdco/HeatCapacity>
- [x] <http://material-digital.de/pmdco/HeatTreatmentProcess>
- [x] <http://material-digital.de/pmdco/HydrogenBond>
- [x] <http://material-digital.de/pmdco/Identifier>
- [x] <http://material-digital.de/pmdco/Image>
- [x] <http://material-digital.de/pmdco/Initiator>
- [x] <http://material-digital.de/pmdco/IonicBond>
- [x] <http://material-digital.de/pmdco/Laboratory>
- [x] <http://material-digital.de/pmdco/LightMicroscopy>
- [x] <http://material-digital.de/pmdco/LoadCell>
- [x] <http://material-digital.de/pmdco/Location>
- [x] <http://material-digital.de/pmdco/Magnetic>
- [x] <http://material-digital.de/pmdco/MajorAxisDiameter>
- [x] <http://material-digital.de/pmdco/Manufacturer>
- [x] <http://material-digital.de/pmdco/ManufacturingNode>
- [x] <http://material-digital.de/pmdco/ManufacturingProcess>
- [x] <http://material-digital.de/pmdco/MaterialDesignation>
- [x] <http://material-digital.de/pmdco/MaterialProperty>
- [x] <http://material-digital.de/pmdco/MaterialQuality>
- [x] <http://material-digital.de/pmdco/MaterialStructure>
- [x] <http://material-digital.de/pmdco/Measurement>
- [x] <http://material-digital.de/pmdco/MeasuringDevice>
- [x] <http://material-digital.de/pmdco/MeasuringProcess>
- [x] <http://material-digital.de/pmdco/Mechanical>
- [x] <http://material-digital.de/pmdco/MechanicalTestingProcess>
- [x] <http://material-digital.de/pmdco/MediaMovement>
- [x] <http://material-digital.de/pmdco/Medium>
- [x] <http://material-digital.de/pmdco/Metadata>
- [x] <http://material-digital.de/pmdco/MetallicBond>
- [x] <http://material-digital.de/pmdco/Method>
- [x] <http://material-digital.de/pmdco/Micropscope>
- [x] <http://material-digital.de/pmdco/MicroscopyProcess>
- [x] <http://material-digital.de/pmdco/MinorAxisDiameter>
- [x] <http://material-digital.de/pmdco/MountingProcess>
- [x] <http://material-digital.de/pmdco/NodeInfo>
- [x] <http://material-digital.de/pmdco/NodeModel>
- [x] <http://material-digital.de/pmdco/NodeName>
- [x] <http://material-digital.de/pmdco/NodeSerialNumber>
- [x] <http://material-digital.de/pmdco/NodeType>
- [x] <http://material-digital.de/pmdco/NodeVersion>
- [x] <http://material-digital.de/pmdco/NonTransformativeAnalysisProcess>
- [x] <http://material-digital.de/pmdco/Norm>
- [x] <http://material-digital.de/pmdco/Note>
- [x] <http://material-digital.de/pmdco/Object>
- [x] <http://material-digital.de/pmdco/Operator>
- [x] <http://material-digital.de/pmdco/Optical>
- [x] <http://material-digital.de/pmdco/OpticalMicroscopy>
- [x] <http://material-digital.de/pmdco/ParticleRadius>
- [x] <http://material-digital.de/pmdco/Pixel>
- [x] <http://material-digital.de/pmdco/PixelDensity>
- [x] <http://material-digital.de/pmdco/PixelPerNanometerUnit>
- [x] <http://material-digital.de/pmdco/PixelUnit>
- [x] <http://material-digital.de/pmdco/PlanningProcess>
- [x] <http://material-digital.de/pmdco/PrecipitateDistance>
- [x] <http://material-digital.de/pmdco/Precision>
- [x] <http://material-digital.de/pmdco/PrimaryData>
- [x] <http://material-digital.de/pmdco/Process>
- [x] <http://material-digital.de/pmdco/ProcessDescription>
- [x] <http://material-digital.de/pmdco/ProcessDuration>
- [x] <http://material-digital.de/pmdco/ProcessIdentifier>
- [x] <http://material-digital.de/pmdco/ProcessingNode>
- [x] <http://material-digital.de/pmdco/Project>
- [x] <http://material-digital.de/pmdco/ProjectIdentifier>
- [x] <http://material-digital.de/pmdco/ProvidedIdentifier>
- [x] <http://material-digital.de/pmdco/QualifyingNodeAnnotation>
- [x] <http://material-digital.de/pmdco/Radiological>
- [x] <http://material-digital.de/pmdco/Radius>
- [x] <http://material-digital.de/pmdco/Rectangular>
- [x] <http://material-digital.de/pmdco/RegionOfInterest>
- [x] <http://material-digital.de/pmdco/Regression>
- [ ] <http://material-digital.de/pmdco/RetortType>
- [x] <http://material-digital.de/pmdco/RockwellHardnessTest>
- [x] <http://material-digital.de/pmdco/SecondaryData>
- [x] <http://material-digital.de/pmdco/SequenceNumber>
- [x] <http://material-digital.de/pmdco/SetPoint>
- [x] <http://material-digital.de/pmdco/Shape>
- [x] <http://material-digital.de/pmdco/SimulationNode>
- [x] <http://material-digital.de/pmdco/SimulationProcess>
- [x] <http://material-digital.de/pmdco/Slide>
- [x] <http://material-digital.de/pmdco/Specimen>
- [x] <http://material-digital.de/pmdco/Squared>
- [x] <http://material-digital.de/pmdco/StartTime>
- [x] <http://material-digital.de/pmdco/Temperature>
- [x] <http://material-digital.de/pmdco/TemperatureChangingProcess>
- [x] <http://material-digital.de/pmdco/TensileTest>
- [x] <http://material-digital.de/pmdco/Thermal>
- [x] <http://material-digital.de/pmdco/ThermalInsulation>
- [x] <http://material-digital.de/pmdco/Thermocouple>
- [x] <http://material-digital.de/pmdco/Time>
- [x] <http://material-digital.de/pmdco/TransformativeAnalysisProcess>
- [x] <http://material-digital.de/pmdco/TransmissionElectronMicroscope>
- [x] <http://material-digital.de/pmdco/TransmissionElectronMicroscopy>
- [ ] <http://material-digital.de/pmdco/ValueObject>
- [x] <http://material-digital.de/pmdco/ValueScope>
- [x] <http://material-digital.de/pmdco/VanderwaalsBond>
- [x] <http://material-digital.de/pmdco/VickersHardnessTest>
- [x] <http://material-digital.de/pmdco/Voxel>
- [x] <http://material-digital.de/pmdco/Weight>
- [x] <http://material-digital.de/pmdco/WeightedXCoordinate>
- [x] <http://material-digital.de/pmdco/WeightedYCoordinate>
- [x] <http://material-digital.de/pmdco/XCoordinate>
- [x] <http://material-digital.de/pmdco/YCoordinate>
- [ ]

**Comment by MarkusSchilling** [comment]
With the last commit (commit 464481476922a86eee0485582cf66749526c27c7), a lot of German labels were included. I only omitted the labels I want to discuss. 
Now, German labels are still missing for: 

- [ ] http://material-digital.de/pmdco/BaseMaterial
- [ ] http://material-digital.de/pmdco/Blank
- [ ] http://material-digital.de/pmdco/ChangeOfTransverseDimension
- [ ] http://material-digital.de/pmdco/CollectionInterfaceHint
- [ ] http://material-digital.de/pmdco/DataCiteMetadata
- [ ] http://material-digital.de/pmdco/DigitalMaterialIdentifier
- [ ] http://material-digital.de/pmdco/FeretDiameter
- [ ] http://material-digital.de/pmdco/PlanningProcess (deleted!)
- [ ] http://material-digital.de/pmdco/RetortType
- [ ] http://material-digital.de/pmdco/ValueObject

**Comment by joergwa** [comment]
FeretDiameter == Äquivalentdurchmesser

**Comment by MarkusSchilling** [comment]
All missing German labels were included in a joint session.
