### ISSUE TITLE
Make IRIs dereferenceable

### ISSUE THREAD

**Issue by joergwa** [materialdigital/core-ontology#17]

**Comment by joergwa** [comment]
To whom do we have to speak, to make this possible?

**Comment by joergwa** [comment]
In todays meeting we discussed this issue with the result to use a w3id prefix `https://w3id.org/pmd/co/` . 

e.g.   `https://w3id.org/pmd/co/Force`

Open for discussion!

**Comment by henkbirkholz** [comment]
I am in favor of w3id

**Comment by BerndBayerlein** [comment]
I am in favor of w3id

**Comment by joergwa** [comment]
https://w3id.org/pmd/co
