### ISSUE TITLE
Discussion, why is prov-o et al not included via owl include or prefixed?

### ISSUE THREAD

**Issue by Kibubu** [materialdigital/core-ontology#21]
Why are there parts of prov-o scattered around the pmd-core-ttl?

Is there a reason not to use https://www.w3.org/TR/owl-ref/#imports-def or at least group included ontologies.

https://github.com/materialdigital/core-ontology/blob/b7e2cd03baaf4eb3520690ec465080e1a7fbb262/pmdco_core.ttl#L3139-L3150

**Comment by joergwa** [comment]
We did not import prov-o explicitly to keep the Protégé view more simple.
