### ISSUE TITLE
Difference "Engineering Strain" and "Percentage Extension"

### ISSUE THREAD

**Issue by joergwa** [materialdigital/core-ontology#25]

**Comment by MarkusSchilling** [comment]
In this case, they are used synonymously. According to the standard (DIN EN ISO 6892-1): 
![extension_strain](https://user-images.githubusercontent.com/83216092/223972205-c766dafd-dddf-4190-94d8-e3c0766035a9.JPG)

**Comment by joergwa** [comment]
removed duplicate
