### ISSUE TITLE
Add TTO concepts to PMDco modules

### ISSUE THREAD

**Issue by MarkusSchilling** [materialdigital/core-ontology#85]
The following concepts originating from the TTO (version 2.0.7) are to be added to corresponding modules with respect to the PMDco 3.0 conceptualization. A TTL file ("pmd_tto_concepts.txt") comprising all these concepts in a 'flat' format including respective annotations and properties (single information 'blocks') is attached to this issue.

# Plain list of concepts (original namespace: @prefix tto: [https://w3id.org/pmd/tto/](https://w3id.org/pmd/tto/))

- ChangeOfTransverseDimension
- CrossheadSeparation
- CrossheadSeparationRate
- DiameterAfterFracture
- Elongation
- EstimatedStrainRateOverTheParallelLength
- ExtensometerGaugeLength
- FinalGaugeLengthAfterFracture
- GaugeLength
- GeometryShape
- LowerYieldStrength
- MaximumForce
- MinimumCrossSectionalAreaAfterFracture
- OriginalCrossSectionalArea
- OriginalDiameter
- OriginalGaugeLength
- OriginalThickness
- OriginalWidth
- ParallelLength
- PercentageElongation
- PercentageElongationAfterFracture
- PercentagePermanentElongation
- PercentagePermanentExtension
- PercentagePlasticExtensionAtMaximumForce
- PercentageReductionOfArea
- PercentageTotalExtensionAtFracture
- PercentageTotalExtensionAtMaximumForce
- PercentageYieldPointExtension
- ProofStrength
- ProofStrengthPlasticExtension
- ProofStrengthTotalExtension
- Rp01
- Rp02
- SizeRelation
- SlopeOfTheElasticPart
- StrainRate
- StressRate
- TensileStrength
- TensileTest
- TensileTestMethod
- TensileTestingMachine
- ThicknessAfterFracture
- TransitionPoint
- TransitionPointTestingRate
- TypeGaugeLengthMarks
- UpperYieldStrength
- WidthAfterFracture
- YieldStrength

[pmd_tto_concepts.txt](https://github.com/user-attachments/files/16249116/pmd_tto_concepts.txt)

**Comment by BerndBayerlein** [comment]
@webhart ... are you aware ?

**Comment by MarkusSchilling** [comment]
There is a new repository [tensile-test-ontology](https://github.com/materialdigital/tensile-test-ontology) which deals with the tensile test ontology. In particular, the actual version of TTO is supposed to be provided there. At the moment, the corresponding pmd_tto.ttl file is connected to the actual version of the PMDco. The concepts mentioned above can be found therein. 
Accordingly, there might not be the need to include all these concepts in the PMDco 3.0. Therefore, this issue can be closed, for now.
