### ISSUE TITLE
Missing descriptions

### ISSUE THREAD

**Issue by joergwa** [materialdigital/core-ontology#97]
Following resources miss a proper description:

https://w3id.org/pmd/co/Ceramic
https://w3id.org/pmd/co/ChemicalCompositionAnalyzingProcess
https://w3id.org/pmd/co/Composite
https://w3id.org/pmd/co/ContinuousSimulation
https://w3id.org/pmd/co/DepartmentRole
https://w3id.org/pmd/co/DeterministicSimulation
https://w3id.org/pmd/co/Discrete-eventSimulation
https://w3id.org/pmd/co/Ferrous_Alloy
https://w3id.org/pmd/co/Glass
https://w3id.org/pmd/co/GravimetricalAnalyzingProcess
https://w3id.org/pmd/co/Group-00-Steel
https://w3id.org/pmd/co/Group-01-Steel
https://w3id.org/pmd/co/Group-02-Steel
https://w3id.org/pmd/co/Group-03-Steel
https://w3id.org/pmd/co/Group-04-Steel
https://w3id.org/pmd/co/Group-05-Steel
https://w3id.org/pmd/co/Group-06-Steel
https://w3id.org/pmd/co/Group-07-Steel
https://w3id.org/pmd/co/Group-08-Steel
https://w3id.org/pmd/co/Group-10-Steel
https://w3id.org/pmd/co/Group-11-Steel
https://w3id.org/pmd/co/Group-12-Steel
https://w3id.org/pmd/co/Group-13-Steel
https://w3id.org/pmd/co/Group-14-Steel
https://w3id.org/pmd/co/Group-15-Steel
https://w3id.org/pmd/co/Group-16-Steel
https://w3id.org/pmd/co/Group-17-Steel
https://w3id.org/pmd/co/Group-18-Steel
https://w3id.org/pmd/co/Group-19-Steel
https://w3id.org/pmd/co/Group-20-Steel
https://w3id.org/pmd/co/Group-21-Steel
https://w3id.org/pmd/co/Group-22-Steel
https://w3id.org/pmd/co/Group-23-Steel
https://w3id.org/pmd/co/Group-24-Steel
https://w3id.org/pmd/co/Group-25-Steel
https://w3id.org/pmd/co/Group-26-Steel
https://w3id.org/pmd/co/Group-27-Steel
https://w3id.org/pmd/co/Group-28-Steel
https://w3id.org/pmd/co/Group-29-Steel
https://w3id.org/pmd/co/Group-30-Steel
https://w3id.org/pmd/co/Group-31-Steel
https://w3id.org/pmd/co/Group-32-Steel
https://w3id.org/pmd/co/Group-33-Steel
https://w3id.org/pmd/co/Group-34-Steel
https://w3id.org/pmd/co/Group-35-Steel
https://w3id.org/pmd/co/Group-36-Steel
https://w3id.org/pmd/co/Group-37-Steel
https://w3id.org/pmd/co/Group-38-Steel
https://w3id.org/pmd/co/Group-39-Steel
https://w3id.org/pmd/co/Group-40-Steel
https://w3id.org/pmd/co/Group-41-Steel
https://w3id.org/pmd/co/Group-42-Steel
https://w3id.org/pmd/co/Group-43-Steel
https://w3id.org/pmd/co/Group-44-Steel
https://w3id.org/pmd/co/Group-45-Steel
https://w3id.org/pmd/co/Group-46-Steel
https://w3id.org/pmd/co/Group-47-Steel
https://w3id.org/pmd/co/Group-48-Steel
https://w3id.org/pmd/co/Group-49-Steel
https://w3id.org/pmd/co/Group-50-Steel
https://w3id.org/pmd/co/Group-51-Steel
https://w3id.org/pmd/co/Group-52-Steel
https://w3id.org/pmd/co/Group-53-Steel
https://w3id.org/pmd/co/Group-54-Steel
https://w3id.org/pmd/co/Group-55-Steel
https://w3id.org/pmd/co/Group-56-Steel
https://w3id.org/pmd/co/Group-57-Steel
https://w3id.org/pmd/co/Group-58-Steel
https://w3id.org/pmd/co/Group-59-Steel
https://w3id.org/pmd/co/Group-60-Steel
https://w3id.org/pmd/co/Group-61-Steel
https://w3id.org/pmd/co/Group-62-Steel
https://w3id.org/pmd/co/Group-63-Steel
https://w3id.org/pmd/co/Group-64-Steel
https://w3id.org/pmd/co/Group-65-Steel
https://w3id.org/pmd/co/Group-66-Steel
https://w3id.org/pmd/co/Group-67-Steel
https://w3id.org/pmd/co/Group-68-Steel
https://w3id.org/pmd/co/Group-69-Steel
https://w3id.org/pmd/co/Group-70-Steel
https://w3id.org/pmd/co/Group-71-Steel
https://w3id.org/pmd/co/Group-72-Steel
https://w3id.org/pmd/co/Group-73-Steel
https://w3id.org/pmd/co/Group-74-Steel
https://w3id.org/pmd/co/Group-75-Steel
https://w3id.org/pmd/co/Group-76-Steel
https://w3id.org/pmd/co/Group-77-Steel
https://w3id.org/pmd/co/Group-78-Steel
https://w3id.org/pmd/co/Group-79-Steel
https://w3id.org/pmd/co/Group-80-Steel
https://w3id.org/pmd/co/Group-81-Steel
https://w3id.org/pmd/co/Group-82-Steel
https://w3id.org/pmd/co/Group-83-Steel
https://w3id.org/pmd/co/Group-84-Steel
https://w3id.org/pmd/co/Group-85-Steel
https://w3id.org/pmd/co/Group-86-Steel
https://w3id.org/pmd/co/Group-87-Steel
https://w3id.org/pmd/co/Group-88-Steel
https://w3id.org/pmd/co/Group-89-Steel
https://w3id.org/pmd/co/Group-90-Steel
https://w3id.org/pmd/co/Group-91-Steel
https://w3id.org/pmd/co/Group-92-Steel
https://w3id.org/pmd/co/Group-93-Steel
https://w3id.org/pmd/co/Group-94-Steel
https://w3id.org/pmd/co/Group-95-Steel
https://w3id.org/pmd/co/Group-96-Steel
https://w3id.org/pmd/co/Group-97-Steel
https://w3id.org/pmd/co/Group-98-Steel
https://w3id.org/pmd/co/Hardness
https://w3id.org/pmd/co/HeatResistingSteel
https://w3id.org/pmd/co/HybridSimulation
https://w3id.org/pmd/co/IndentationHardness
https://w3id.org/pmd/co/InitiatorRole
https://w3id.org/pmd/co/LaboratoryRole
https://w3id.org/pmd/co/ManufacturerRole
https://w3id.org/pmd/co/MechanicalQuality
https://w3id.org/pmd/co/Metal
https://w3id.org/pmd/co/MiscelaneousSteel
https://w3id.org/pmd/co/MorphologicQuality
https://w3id.org/pmd/co/NaturalOrganicMaterial
https://w3id.org/pmd/co/Object
https://w3id.org/pmd/co/OperatorRole
https://w3id.org/pmd/co/Organization
https://w3id.org/pmd/co/Person
https://w3id.org/pmd/co/PhysicalSimulation
https://w3id.org/pmd/co/Polymer
https://w3id.org/pmd/co/PortionOfMatter
https://w3id.org/pmd/co/qualities/1D
https://w3id.org/pmd/co/qualities/2D
https://w3id.org/pmd/co/qualities/AccousticAbsorptionCoefficient
https://w3id.org/pmd/co/qualities/AccousticProperty
https://w3id.org/pmd/co/qualities/Age
https://w3id.org/pmd/co/qualities/AggregateState
https://w3id.org/pmd/co/qualities/ApplicationOfAccousticWave
https://w3id.org/pmd/co/qualities/ApplicationOfElasticImpact
https://w3id.org/pmd/co/qualities/ApplicationOfElectricField
https://w3id.org/pmd/co/qualities/ApplicationOfHeatFlux
https://w3id.org/pmd/co/qualities/ApplicationOfMagneticField
https://w3id.org/pmd/co/qualities/ApplicationOfMechanicalLoad
https://w3id.org/pmd/co/qualities/ApplicationOfSubstance
https://w3id.org/pmd/co/qualities/ASTM_Grainsize
https://w3id.org/pmd/co/qualities/AtomicStructure
https://w3id.org/pmd/co/qualities/BoilingPoint
https://w3id.org/pmd/co/qualities/Brinell2.5_62.5_ISO_6506
https://w3id.org/pmd/co/qualities/BrinellHardness
https://w3id.org/pmd/co/qualities/Bulk
https://w3id.org/pmd/co/qualities/BulkModulus
https://w3id.org/pmd/co/qualities/ChangeOfAggregateState
https://w3id.org/pmd/co/qualities/ChangeOfPhase
https://w3id.org/pmd/co/qualities/ChangeOfTemperature
https://w3id.org/pmd/co/qualities/ChemicalComposition
https://w3id.org/pmd/co/qualities/ChemicalPotential
https://w3id.org/pmd/co/qualities/CorpuscularIrradiation
https://w3id.org/pmd/co/qualities/CrackGrowth
https://w3id.org/pmd/co/qualities/CrystallStructure
https://w3id.org/pmd/co/qualities/DefectDensity
https://w3id.org/pmd/co/qualities/Deformation
https://w3id.org/pmd/co/qualities/Density
https://w3id.org/pmd/co/qualities/DeteriorativeProperty
https://w3id.org/pmd/co/qualities/DielectricConstant
https://w3id.org/pmd/co/qualities/ElasticModulus
https://w3id.org/pmd/co/qualities/ElectricalConductivity
https://w3id.org/pmd/co/qualities/ElectricalProperty
https://w3id.org/pmd/co/qualities/ElectricPotential
https://w3id.org/pmd/co/qualities/EmissionOfAccousticWave
https://w3id.org/pmd/co/qualities/EmissionOfCorpuscularRadiation
https://w3id.org/pmd/co/qualities/EmissionOfRadiation
https://w3id.org/pmd/co/qualities/EmissionOfWaveRadiation
https://w3id.org/pmd/co/qualities/EvolutionOfDamage
https://w3id.org/pmd/co/qualities/FormationOfNotchOrScratch
https://w3id.org/pmd/co/qualities/GrainSizeDistribution
https://w3id.org/pmd/co/qualities/Half-Life
https://w3id.org/pmd/co/qualities/HeatCapacity
https://w3id.org/pmd/co/qualities/Image
https://w3id.org/pmd/co/qualities/in_response_to
https://w3id.org/pmd/co/qualities/IndexOfRefraction
https://w3id.org/pmd/co/qualities/Macrostructure
https://w3id.org/pmd/co/qualities/MagneticProperty
https://w3id.org/pmd/co/qualities/Map
https://w3id.org/pmd/co/qualities/MaterialPropertyMeasure
https://w3id.org/pmd/co/qualities/MaterialStructure
https://w3id.org/pmd/co/qualities/MechanicalProperty
https://w3id.org/pmd/co/qualities/MeltingPoint
https://w3id.org/pmd/co/qualities/MetallographicTexture
https://w3id.org/pmd/co/qualities/Microstructure
https://w3id.org/pmd/co/qualities/MohsHardness
https://w3id.org/pmd/co/qualities/MorphologicalProperty
https://w3id.org/pmd/co/qualities/MorphologicQuality
https://w3id.org/pmd/co/qualities/OccurenceOfChemicalReaction
https://w3id.org/pmd/co/qualities/OccurenceOfElecticField
https://w3id.org/pmd/co/qualities/OccurenceOfMagneticField
https://w3id.org/pmd/co/qualities/OpticalProperty
https://w3id.org/pmd/co/qualities/PassingOfTime
https://w3id.org/pmd/co/qualities/PhaseBoundary
https://w3id.org/pmd/co/qualities/PoleFigure
https://w3id.org/pmd/co/qualities/PolyCrystallineGrainStucture
https://w3id.org/pmd/co/qualities/PoreGrowth
https://w3id.org/pmd/co/qualities/Pressure
https://w3id.org/pmd/co/qualities/Reflectivity
https://w3id.org/pmd/co/qualities/Response
https://w3id.org/pmd/co/qualities/Scalar
https://w3id.org/pmd/co/qualities/SpecificSurfaceArea
https://w3id.org/pmd/co/qualities/Spectrum
https://w3id.org/pmd/co/qualities/SpeedOfSound
https://w3id.org/pmd/co/qualities/Stiffness
https://w3id.org/pmd/co/qualities/stimulated_by
https://w3id.org/pmd/co/qualities/stimulates
https://w3id.org/pmd/co/qualities/Stimulation
https://w3id.org/pmd/co/qualities/Strenght
https://w3id.org/pmd/co/qualities/StructuralAndChemicalDecay
https://w3id.org/pmd/co/qualities/SubatomicStructure
https://w3id.org/pmd/co/qualities/SublimationPoint
https://w3id.org/pmd/co/qualities/Surface
https://w3id.org/pmd/co/qualities/Temperature
https://w3id.org/pmd/co/qualities/TemporalProperty
https://w3id.org/pmd/co/qualities/ThermalConductivity
https://w3id.org/pmd/co/qualities/ThermalProperty
https://w3id.org/pmd/co/qualities/ThermodynamicQuality
https://w3id.org/pmd/co/qualities/TimeSeries
https://w3id.org/pmd/co/qualities/TriplePoint
https://w3id.org/pmd/co/qualities/WaverIrradiation
https://w3id.org/pmd/co/ReboundHardness
https://w3id.org/pmd/co/ScratchHardness
https://w3id.org/pmd/co/SimulatedObject
https://w3id.org/pmd/co/SimulatingProcess
https://w3id.org/pmd/co/StochasticSimulation
https://w3id.org/pmd/co/StructuralAndOrPVAndOrEngineeringSteel
https://w3id.org/pmd/co/ToolSteel
https://w3id.org/pmd/co/UrformenAusDemBreiigenOderPastösenZustand
https://w3id.org/pmd/co/UrformenAusDemFlüssigenZustand
https://w3id.org/pmd/co/UrformenAusDemGasförmigenOderDampfförmigenZustand
https://w3id.org/pmd/co/UrformenAusDemIonisiertenZustand
https://w3id.org/pmd/co/UrformenAusDemKörnerförmigenOderPulverförmigenZustand
https://w3id.org/pmd/co/UrformenAusDemPlastischenZustand
https://w3id.org/pmd/co/UrformenAusDemSpanförmigenOderFaserförmigenZustand
https://w3id.org/pmd/co/UrformenDurchAdditiveFertigung
https://w3id.org/pmd/co/UrformenDurchSchweissen

**Comment by BerndBayerlein** [comment]
[https://w3id.org/pmd/co/UrformenAusDemBreiigenOderPastösenZustand](https://w3id.org/pmd/co/UrformenAusDemBreiigenOderPast%C3%B6senZustand)
[https://w3id.org/pmd/co/UrformenAusDemFlüssigenZustand](https://w3id.org/pmd/co/UrformenAusDemFl%C3%BCssigenZustand)
[https://w3id.org/pmd/co/UrformenAusDemGasförmigenOderDampfförmigenZustand](https://w3id.org/pmd/co/UrformenAusDemGasf%C3%B6rmigenOderDampff%C3%B6rmigenZustand)
https://w3id.org/pmd/co/UrformenAusDemIonisiertenZustand
[https://w3id.org/pmd/co/UrformenAusDemKörnerförmigenOderPulverförmigenZustand](https://w3id.org/pmd/co/UrformenAusDemK%C3%B6rnerf%C3%B6rmigenOderPulverf%C3%B6rmigenZustand)
https://w3id.org/pmd/co/UrformenAusDemPlastischenZustand
[https://w3id.org/pmd/co/UrformenAusDemSpanförmigenOderFaserförmigenZustand](https://w3id.org/pmd/co/UrformenAusDemSpanf%C3%B6rmigenOderFaserf%C3%B6rmigenZustand)
https://w3id.org/pmd/co/UrformenDurchAdditiveFertigung
https://w3id.org/pmd/co/UrformenDurchSchweissen

@joergwa these should be all fixed (english label, full annotation properties, ...) with my update of the manufacturing module today.

**Comment by joergwa** [comment]
https://w3id.org/pmd/co/PMD_0000004, Material Entity Aggregate
https://w3id.org/pmd/co/PMD_0000006, Material Structure
https://w3id.org/pmd/co/PMD_0000501, 1D
https://w3id.org/pmd/co/PMD_0000502, 2D
https://w3id.org/pmd/co/PMD_0000503, ASTM  Grainsize
https://w3id.org/pmd/co/PMD_0000505, Accoustic Absorption Coefficient
https://w3id.org/pmd/co/PMD_0000506, Accoustic Property
https://w3id.org/pmd/co/PMD_0000511, Age
https://w3id.org/pmd/co/PMD_0000512, Aggregate State
https://w3id.org/pmd/co/PMD_0000517, Application Of Accoustic Wave
https://w3id.org/pmd/co/PMD_0000518, Application Of Elastic Impact
https://w3id.org/pmd/co/PMD_0000519, Application Of Electric Field
https://w3id.org/pmd/co/PMD_0000520, Application Of Heat Flux
https://w3id.org/pmd/co/PMD_0000521, Application Of Magnetic Field
https://w3id.org/pmd/co/PMD_0000522, Application Of Mechanical Load
https://w3id.org/pmd/co/PMD_0000523, Application Of Substance
https://w3id.org/pmd/co/PMD_0000526, Atomic Structure
https://w3id.org/pmd/co/PMD_0000535, Boiling Point
https://w3id.org/pmd/co/PMD_0000536, Brinell 2.5 62.5 ISO 6506
https://w3id.org/pmd/co/PMD_0000537, Brinell Hardness
https://w3id.org/pmd/co/PMD_0000538, Bulk
https://w3id.org/pmd/co/PMD_0000539, Bulk Modulus
https://w3id.org/pmd/co/PMD_0000546, Ceramic
https://w3id.org/pmd/co/PMD_0000547, Change Of Aggregate State
https://w3id.org/pmd/co/PMD_0000548, Change Of Phase
https://w3id.org/pmd/co/PMD_0000549, Change Of Temperature
https://w3id.org/pmd/co/PMD_0000551, Chemical Composition
https://w3id.org/pmd/co/PMD_0000553, Chemical Potential
https://w3id.org/pmd/co/PMD_0000577, Composite
https://w3id.org/pmd/co/PMD_0000585, Continuous Simulation
https://w3id.org/pmd/co/PMD_0000586, Corpuscular Irradiation
https://w3id.org/pmd/co/PMD_0000587, Crack Growth
https://w3id.org/pmd/co/PMD_0000591, Crystall Structure
https://w3id.org/pmd/co/PMD_0000595, Defect Density
https://w3id.org/pmd/co/PMD_0000596, Deformation
https://w3id.org/pmd/co/PMD_0000597, Density
https://w3id.org/pmd/co/PMD_0000599, Department Role
https://w3id.org/pmd/co/PMD_0000600, Deteriorative Property
https://w3id.org/pmd/co/PMD_0000601, Deterministic Simulation
https://w3id.org/pmd/co/PMD_0000604, Dielectric Constant
https://w3id.org/pmd/co/PMD_0000613, Discrete-event Simulation
https://w3id.org/pmd/co/PMD_0000618, Elastic Modulus
https://w3id.org/pmd/co/PMD_0000619, Electric Potential
https://w3id.org/pmd/co/PMD_0000620, Electrical Conductivity
https://w3id.org/pmd/co/PMD_0000621, Electrical Property
https://w3id.org/pmd/co/PMD_0000627, Emission Of Accoustic Wave
https://w3id.org/pmd/co/PMD_0000628, Emission Of Corpuscular Radiation
https://w3id.org/pmd/co/PMD_0000629, Emission Of Radiation
https://w3id.org/pmd/co/PMD_0000630, Emission Of Wave Radiation
https://w3id.org/pmd/co/PMD_0000635, Evolution Of Damage
https://w3id.org/pmd/co/PMD_0000639, Ferrous  Alloy
https://w3id.org/pmd/co/PMD_0000645, Formation Of Notch Or Scratch
https://w3id.org/pmd/co/PMD_0000661, Glass
https://w3id.org/pmd/co/PMD_0000663, Grain
https://w3id.org/pmd/co/PMD_0000663, Korn
https://w3id.org/pmd/co/PMD_0000664, Grain Size Distribution
https://w3id.org/pmd/co/PMD_0000768, Half-Life
https://w3id.org/pmd/co/PMD_0000773, Hardness
https://w3id.org/pmd/co/PMD_0000777, Heat Capacity
https://w3id.org/pmd/co/PMD_0000778, Heat Resisting Steel
https://w3id.org/pmd/co/PMD_0000786, Hybrid Simulation
https://w3id.org/pmd/co/PMD_0000787, Image
https://w3id.org/pmd/co/PMD_0000789, Indentation Hardness
https://w3id.org/pmd/co/PMD_0000790, Index Of Refraction
https://w3id.org/pmd/co/PMD_0000793, Initiator Role
https://w3id.org/pmd/co/PMD_0000815, Laboratory Role
https://w3id.org/pmd/co/PMD_0000824, Macrostructure
https://w3id.org/pmd/co/PMD_0000825, Magnetic Property
https://w3id.org/pmd/co/PMD_0000831, Manufacturer Role
https://w3id.org/pmd/co/PMD_0000834, Map
https://w3id.org/pmd/co/PMD_0000842, Material Property Measure
https://w3id.org/pmd/co/PMD_0000845, Matrix
https://w3id.org/pmd/co/PMD_0000848, Mechanical Property
https://w3id.org/pmd/co/PMD_0000850, Mechanical Quality
https://w3id.org/pmd/co/PMD_0000851, Melting Point
https://w3id.org/pmd/co/PMD_0000852, Metal
https://w3id.org/pmd/co/PMD_0000853, Metallographic Texture
https://w3id.org/pmd/co/PMD_0000857, Microstructure
https://w3id.org/pmd/co/PMD_0000860, Miscelaneous Steel
https://w3id.org/pmd/co/PMD_0000861, Mohs Hardness
https://w3id.org/pmd/co/PMD_0000863, Morphologic Quality
https://w3id.org/pmd/co/PMD_0000864, Morphological Property
https://w3id.org/pmd/co/PMD_0000868, Natural Organic Material
https://w3id.org/pmd/co/PMD_0000869, Occurence Of Chemical Reaction
https://w3id.org/pmd/co/PMD_0000870, Occurence Of Electic Field
https://w3id.org/pmd/co/PMD_0000871, Occurence Of Magnetic Field
https://w3id.org/pmd/co/PMD_0000873, Operator Role
https://w3id.org/pmd/co/PMD_0000877, Optical Property
https://w3id.org/pmd/co/PMD_0000879, Organization
https://w3id.org/pmd/co/PMD_0000880, Passing Of Time
https://w3id.org/pmd/co/PMD_0000881, Person
https://w3id.org/pmd/co/PMD_0000882, Phase Boundary
https://w3id.org/pmd/co/PMD_0000884, Physical Simulation
https://w3id.org/pmd/co/PMD_0000885, Pole Figure
https://w3id.org/pmd/co/PMD_0000887, Poly Crystalline Grain Stucture
https://w3id.org/pmd/co/PMD_0000888, Polymer
https://w3id.org/pmd/co/PMD_0000889, Pore Growth
https://w3id.org/pmd/co/PMD_0000890, PortionOFConnectedMatter
https://w3id.org/pmd/co/PMD_0000891, PortionOfDisconnectedMatter
https://w3id.org/pmd/co/PMD_0000892, Portion Of Matter
https://w3id.org/pmd/co/PMD_0000893, Powder
https://w3id.org/pmd/co/PMD_0000896, Pressure
https://w3id.org/pmd/co/PMD_0000910, Rebound Hardness
https://w3id.org/pmd/co/PMD_0000911, Reflectivity
https://w3id.org/pmd/co/PMD_0000915, Response
https://w3id.org/pmd/co/PMD_0000921, Scalar
https://w3id.org/pmd/co/PMD_0000924, Scratch Hardness
https://w3id.org/pmd/co/PMD_0000930, Simulated Object
https://w3id.org/pmd/co/PMD_0000931, Simulating Process
https://w3id.org/pmd/co/PMD_0000942, Specific Surface Area
https://w3id.org/pmd/co/PMD_0000946, Spectrum
https://w3id.org/pmd/co/PMD_0000947, Speed Of Sound
https://w3id.org/pmd/co/PMD_0000949, Stiffness
https://w3id.org/pmd/co/PMD_0000950, Stimulation
https://w3id.org/pmd/co/PMD_0000951, Stochastic Simulation
https://w3id.org/pmd/co/PMD_0000952, Strenght
https://w3id.org/pmd/co/PMD_0000953, Structural And Chemical Decay
https://w3id.org/pmd/co/PMD_0000954, Structural And Or PV And Or 
https://w3id.org/pmd/co/PMD_0000958, Subatomic Structure
https://w3id.org/pmd/co/PMD_0000961, Sublimation Point
https://w3id.org/pmd/co/PMD_0000965, Surface
https://w3id.org/pmd/co/PMD_0000967, Temperature
https://w3id.org/pmd/co/PMD_0000972, Temporal Property
https://w3id.org/pmd/co/PMD_0000978, Thermal Conductivity
https://w3id.org/pmd/co/PMD_0000981, Thermal Property
https://w3id.org/pmd/co/PMD_0000985, Thermodynamic Quality
https://w3id.org/pmd/co/PMD_0000992, Time Series
https://w3id.org/pmd/co/PMD_0000993, Tool Steel
https://w3id.org/pmd/co/PMD_0000996, Triple Point
https://w3id.org/pmd/co/PMD_0001008, Waver Irradiation
https://w3id.org/pmd/co/PMD_0001028, in response to
https://w3id.org/pmd/co/PMD_0001030, stimulated by
https://w3id.org/pmd/co/PMD_0001031, stimulates

**Comment by MarkusSchilling** [comment]
With the two latest commits of today (commits: [a23a814](https://github.com/materialdigital/core-ontology/commit/a23a814e2454a7d890ddebf5951c21f18cf3ef16) and [8a00174](https://github.com/materialdigital/core-ontology/commit/8a00174ff4f9dd9a01284e63270e28d9fb92117a), there are supposed to be definitions of all classes (using skos:definition) in natural English language momentarily present in the PMDco. Furthermore, some typos were fixed (e.g., label of "[https://w3id.org/pmd/co/PMD_0000952](https://w3id.org/pmd/co/PMD_0000952), Strenght" changed to "Strength"). However, some classes might have been overseen - nobody's perfect - so I will double-check later on. In addition, the object properties, such as 

- [https://w3id.org/pmd/co/PMD_0001028](https://w3id.org/pmd/co/PMD_0001028), in response to
- [https://w3id.org/pmd/co/PMD_0001030](https://w3id.org/pmd/co/PMD_0001030), stimulated by
- [https://w3id.org/pmd/co/PMD_0001031](https://w3id.org/pmd/co/PMD_0001031), stimulates

are not defined (skos:definition), yet.
