### ISSUE TITLE
The documentation miro board is editable by anyone

### ISSUE THREAD

**Issue by Sondeluz** [materialdigital/core-ontology#99]
Hello! I was browsing the documentation for your ontology, and I noticed that I could freely edit the documentation miro board. If this was not intended, I would set it to read-only as otherwise it may get vandalized or edited by mistake.

**Comment by joergwa** [comment]
Thank you for your advice. We decided to leave it open so its easier to contribute. We create regular copies, so that we can recreate it, if needed.
